export const UPDATE_CELLS = 'UPDATE_CELLS';
export const RESET_BOMBS_LEFT = 'RESET_BOMBS_LEFT';
export const DECREMENT_BOMBS_LEFT = 'DECREMENT_BOMBS_LEFT';
export const INCREMENT_BOMBS_LEFT = 'INCREMENT_BOMBS_LEFT';
export const SET_STARTED = 'SET_STARTED';
export const SHOW_END_WINDOW = 'SHOW_END_WINDOW';
export const HIDE_END_WINDOW = 'HIDE_END_WINDOW';