export const UPDATE_CELLS = 'UPDATE_CELLS';
export const RESET_BOMBS_LEFT = 'RESET_BOMBS_LEFT';
export const DECREASE_BOMBS_LEFT = 'DECREASE_BOMBS_LEFT';
export const INCREASE_BOMBS_LEFT = 'INCREASE_BOMBS_LEFT';
export const SET_STARTED = 'SET_STARTED';
export const SET_TIME = 'SET_TIME';
export const INCREASE_TIME = 'INCREASE_TIME';

export const SHOW_END_WINDOW = 'SHOW_END_WINDOW';
export const HIDE_END_WINDOW = 'HIDE_END_WINDOW';
export const SET_RECORDS = 'SET_RECORDS';
